### ISSUE TITLE
Anfangswert Zählerstand

### ISSUE THREAD

**Issue by iob2020** [msussek/arduino#1]
Hallo, kann es sein, das in dem Blockly Skript die Berücksichtigung des Anfangswertes fehlt?

**Comment by msussek** [comment]
Hallo, 

hierzu bitte einfach den Wert des Datenpunktes javascript.0.Gas.Verbrauch_Volumen auf den Anfangswert des Zählers setzen.

Das Blockly Script addiert einfach nur den Verbrauch anhand der gezahlten Impulse zum vorherigen Wert des Datenpunktes hinzu.

Somit sollte der Wert des Datenpunktes synchron mit dem Wert des Zählers steigen.

Es können auch Messfehler, die mit der Zeit auftreten können (zum Beispiel durch Ausfälle des Wemos, Übertragungsfehler oder Mehrfachauslösungen falls der Zähler genau am Magnet stehen bleibt etc.), korrigiert werden indem man den Datenpunkt wieder auf den tatsächlichen Wert des Zählers setzt.

Viele Grüße, 
Marco
