### ISSUE TITLE
Verbrauch wird bei neustart nicht upgedatet

### ISSUE THREAD

**Issue by muerzi** [msussek/arduino#2]
Hallo Marco,

sehr tolles Projekt das du da auf die Beine gestellt hast.

Bin beim testen jedoch auf ein kleines Problem gestoßen.
Wenn der ESP neu gestartet wird und vor der ersten MQTT Nachricht ein Impuls gezählt wird, ändert sich Verbrauch_Volumen nicht, 

Habe im Blockly folgende Änderung gemacht bei welcher das Problem dann nicht auftritt

![image](https://user-images.githubusercontent.com/4198159/79694637-e39f3a80-8271-11ea-95c4-ed0c7af21f40.png)

lg Stefan

**Comment by msussek** [comment]
Hallo Stefan,

vielen Dank für deine Anmerkung. Ja, da hast du Recht, im Falle eines Resets des ESPs besteht eine Implementierungslücke, ich habe das nun gefixed und dabei gleich noch einen weiteren Fall behandelt: 

Sollte der Impulszählerwert tatsächlich einmal überlaufen (sollte eigentlich nicht passieren bei einem long, aber wer weiß das schon), reagiert das Script nun damit, dass deltaWert auf 1 gesetzt wird, in diesem Fall gehe ich vereinfacht davon aus, dass nur ein Impuls seit dem letzten Ausleseintervall gezählt wurde (kann fehlerbehaftet sein). Andernfalls würde deltaWert auf eine große negative Zahl gesetzt werden und die Berechnungen würden auf Folgefehler laufen.

Das ganze sieht dann wie folgt aus:

![image](https://user-images.githubusercontent.com/57870078/79703228-c3d83880-82aa-11ea-93c1-d89d572a4e4a.png)

Ich pushe den Export meines geänderten Scripts nun auch auf Github.
