### ISSUE TITLE
Falsche Signale vom Reed-Kontakt

### ISSUE THREAD

**Issue by muerzi** [msussek/arduino#3]
Hallo Marco,

seit einigen Tagen läuft nun dein Code bei mir auf einen nodemcu.
Manchmal werden jedoch die interrupts falsch ausgelöst.

Ich habe die korrekte position des Reed-Kontakts bei meinem Zähler gefunden (ganz links in der Asusbuchtung). Nach vergrößern der entprellzeit auf 120sek (!!) sind die meisten falschen signale nun weg. 

Heute hatte ich den fall das das Zählwerk genau an der Magnetposition stehen blieb und nach dem erneuten Anlaufen der Herizung ( 2 Stunden später) ich wieder ein falsches Signal bekam.

Ich denke das der interrupt im code bei jedem "CHANGE" triggert und nicht bei RISING oder FALLING. 

Was denkst du hierzu?

lg Stefan

**Comment by msussek** [comment]
Hallo,

wieso wurde denn der Issue geschlossen, hast du das Problem bereits lösen können? 

Ansonsten würde ich bei dieser Fehlerbeschreibung darauf tippen, dass der interne Pullup-Widerstand des NodeMCU nicht ausreicht, um den Eingang im Potentialfreien Zustand störungsfrei auf High zu ziehen. 

Du könntest mal versuchen, zusätzlich einen externen Pullup Widerstand zu verwenden, Schaltung siehe https://rn-wissen.de/wiki/index.php/Pullup_Pulldown_Widerstand

Einfach den Eingang, an dem der Reed-Kontakt hängt über einen 1 kOhm Widerstand mit dem 3 Volt Anschluss verbinden, dadurch wird er hochohnig auf High gezogen. Schließt dann der Reed-Kontakt den Stromkreis gegen Masse, fällt der Pegel am Eingang auf Low, da der Reed-Kontakt niederohmig ist.

Viel Erfolg! 

Viele Grüße, 
Marco

**Comment by muerzi** [comment]
Hi. 

Hab erst nachdem ich das issue geöffnet habe im cide gesehn das der interrupt mit fallimg getriggert wird... deswegen hab ich den geschlossen. Ich werde mal ein paar tage noch beobachten und es dann mit einem externen pullup versuchen.

Danke &lg
Stefan
